### PR TITLE
Add support for Conda environments, just like python environments.

### PR DESCRIPTION
**Pull request by tovrstra**
Anaconda environments behave in many ways like Python environments. Therefore, it is also useful to know which Conda environment is loaded.

These changes work with traditional Anaconda and its derivatives, such as Miniconda, Micromamba, etc.

P.S. I'm not an advanced bash coder, so all comments welcome. I'm happy to learn. This just seemed to work well for me. Thanks!

### CODE REVIEW

**Comment by napalm255** [comment]
Code looks good, I'll give it a spin.

**Comment by tovrstra** [comment]
@napalm255 Is there a possibility for you to review and/or merge the PR and #19 in the near future?

I'd like to include powerbash in a setup for a course, and it would be nice to refer to the official repo instead of [my branch where I merged these two PRs](https://github.com/tovrstra/powerbash/tree/merged1).

Thank you!

**Review by napalm255 — CHANGES_REQUESTED** [review]
I moved around the README.md. Need to update accordingly.

**Comment by tovrstra** [comment]
@napalm255 Thanks for looking into this. I've merged the master branch into the conda branch and handled the conflict.

**Pull request merged**
