### PR TITLE
Update powerbash.sh

### PR DESCRIPTION
**Pull request by johnfraney**
Add Python virtualenv information to the beginning of the prompt. You will probably prefer a different symbol, but I couldn't resist the joke.

### CODE REVIEW

**Comment by napalm255** [comment]
I added 'py' to the variable names in case there are any additional python related features added later. I changed the symbol - i assume it was the snake but showed as garbage on my system so i changed it to a simple arrow. I also updated bash completion for the new feature.

**Comment by johnfraney** [comment]
Those are all good changes. Thanks for the script! I'm using it in place of
bash-powerline.sh and it's treating me well so far.

**Comment by napalm255** [comment]
That's awesome to hear! Glad others can take advantage of it. We actually forked from bash-powerline and decided to practically rewrite the entire thing. Keep the feedback, pull requests and bug reports coming!

**Comment by johnfraney** [comment]
I thought some of the code looked familiar. I'm going to be using it on my
OS X and Linux systems, so if I think of anything, I'll get in touch!

**Pull request merged**
